channels:
- conda-forge
dependencies:
- python=3.12.6
- pip<=25.0
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pathlib==1.0.1
  - psutil==6.0.0
  - scikit-learn==1.4.2
  - scipy==1.11.4
name: mlflow-env
